name: user_repository
description: the Repo that handles user
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  font_awesome_flutter: ^10.6.0
  flutterfire_ui: ^0.4.3+20

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
